# Generated by Django 3.1.7 on 2021-04-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_header_product_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='none', max_length=50, null=True)),
                ('details', models.TextField(blank=True, default='none', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
