# Generated by Django 3.1.7 on 2021-04-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bg_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sbg_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sbg_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sgb_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
