# Generated by Django 3.1.7 on 2021-04-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210402_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkingProcess',
        ),
    ]
