# Generated by Django 3.1.7 on 2021-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_workingprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bg_header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
