# Generated by Django 3.1.7 on 2021-04-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_bg_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='how_it_works_five',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_five_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_four',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_four_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_one',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_one_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_six',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_six_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_three',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_three_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_two',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_it_works_two_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
