# Generated by Django 3.1.7 on 2021-04-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('detail', models.TextField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
