# Generated by Django 3.1.7 on 2021-04-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_sbg_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sbg_header',
            new_name='sbg_header_two',
        ),
        migrations.AddField(
            model_name='product',
            name='sbg_header_one',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
