# Generated by Django 3.1.7 on 2021-04-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shc_one', models.CharField(blank=True, max_length=200, null=True)),
                ('shc_two', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
