# Generated by Django 3.1.7 on 2021-04-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_serviceheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceheader',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service'),
        ),
    ]
