# Generated by Django 3.1.7 on 2021-04-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_serviceprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprocess',
            name='process_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
