# Generated by Django 3.1.7 on 2021-04-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210404_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
