# Generated by Django 3.1.7 on 2021-04-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210405_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topfeature',
            name='detail_two',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
