# Generated by Django 3.1.7 on 2021-04-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210405_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('process_title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
        ),
    ]
