# Generated by Django 3.1.7 on 2021-04-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210405_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeature',
            name='process_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
