# Generated by Django 3.1.7 on 2021-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210406_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='fav',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
