# Generated by Django 3.1.7 on 2021-04-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210407_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebody',
            name='sbhimage',
        ),
    ]
