# Generated by Django 3.1.7 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_servicebody_sbhimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebody',
            name='sbhimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
